# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def migrate_blocks(apps, schema_editor):
    Activity = apps.get_model('tracking', 'Activity')
    for activity in Activity.objects.all():
        if activity.blocks.count() == 1:
            block = activity.blocks.all()[0]
            activity.from_time = block.from_time
            activity.to_time = block.to_time
            activity.save()
        else:
            for block in activity.blocks.all():
                Activity(from_time=block.from_time,
                         to_time=block.to_time,
                         comment=activity.comment,
                         date=activity.date,
                         task=activity.task,
                         user=activity.user).save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_absence_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='transfered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='from_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_blocks),
        migrations.RemoveField(
            model_name='activityblock',
            name='activity',
        ),
        migrations.DeleteModel(
            name='ActivityBlock',
        ),
    ]
