version: "3.7"

services:
  backend:
    build:
      context: .
      args:
        REQUIREMENTS: requirements-dev.txt
    depends_on:
      - mailhog
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - EMAIL_URL=smtp://mailhog:1025
      - DJANGO_OIDC_USERNAME_CLAIM=preferred_username
    volumes:
      - ./:/app
    command: /bin/sh -c "wait-for-it.sh -t 60 db:5432 -- ./manage.py migrate && ./manage.py serve --port 80 --req-queue-len=${HURRICANE_REQ_QUEUE_LEN:-250} --autoreload --static"
    ports:
      - "81:81"
    networks:
      - timed.local

  frontend:
    image: adfinissygroup/timed-frontend:latest
    ports:
      - 4200:80
    environment:
      - TIMED_SSO_CLIENT_HOST=http://timed.local/auth/realms/timed/protocol/openid-connect
      - TIMED_SSO_CLIENT_ID=timed-public
    networks:
      - timed.local

  keycloak:
    image: jboss/keycloak:10.0.1
    volumes:
      - ./dev-config/keycloak-config.json:/etc/keycloak/keycloak-config.json:rw
    depends_on:
      - db
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_USER=timed
      - DB_DATABASE=timed
      - DB_PASSWORD=timed
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    # start keycloak with the following command to perform an export of the `timed` realm.
    #command: ["-Dkeycloak.migration.action=export", "-Dkeycloak.migration.realmName=timed", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/etc/keycloak/keycloak-config.json", "-b", "0.0.0.0"]
    command: ["-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/etc/keycloak/keycloak-config.json", "-b", "0.0.0.0"]
    networks:
      - timed.local

  proxy:
    image: nginx:1.17.10-alpine
    ports:
      - 80:80
    volumes:
      - ./dev-config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      timed.local:
        aliases:
          - timed.local

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    environment:
      - MH_UI_WEB_PATH=mailhog
    networks:
      - timed.local
