version: "3"

volumes:
  dbdata:

services:
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresq
    environment:
      - POSTGRES_USER=timed
      - POSTGRES_PASSWORD=timed
  backend:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DJANGO_DATABASE_HOST=db
      - ENV=docker
      - STATIC_ROOT=/var/www/static
