version: '2'
services:
  db:
    image: postgres:9.4
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=timed
      - POSTGRES_PASSWORD=timed
  backend:
    build: .
    ports:
      - '8000:80'
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_DATABASE_HOST=db
      - ENV=docker
      - STATIC_ROOT=/var/www/static
