# Generated by Django 4.2.11 on 2024-04-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_package_price_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPassword',
        ),
    ]
