# Generated by Django 4.2.11 on 2024-04-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_amount_invoiced_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'ordering': ('name',)},
        ),
    ]
