---
name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: .venv
          key: poetry-${{ hashFiles('poetry.lock')}}
          restore-keys: |
            peotry-
      - name: Build the project
        run: |
          echo "ENV=dev" > .env
          docker-compose up -d --build backend
      - name: Lint the code
        run: |
          docker-compose run --rm backend black --check .
          docker-compose run --rm backend flake8
      - name: Check for missing migrations
        run: docker-compose run --rm backend python manage.py makemigrations --check --dry-run --no-input
      - name: Run pytest
        run: docker-compose run --rm backend pytest --no-cov-on-fail --cov --create-db -vv
